### ISSUE TITLE
Is the flip needed?

### ISSUE THREAD

**Issue by jkudish** [unicodeveloper/laravel-password#10]
Hey there,

Thanks for this package, it's great :)

I'm just wondering, why do you need [to flip the array](https://github.com/unicodeveloper/laravel-password/blob/master/src/DumbPasswordServiceProvider.php#L33) of dumb passwords? No scientific measures here, but this operation seems to be kind of memory intensive and take a bit of time to run. It is causing some of my tests in a project to fail due to running out of memory.

If I remove it, everything still seems to work as expected, and run a bit faster and use less memory.

Let me know. I'd be happy to submit a PR to remove it.

Thanks! 😄

**Comment by jkudish** [comment]
Also, perhaps the array could be cached?

**Comment by unicodeveloper** [comment]
@jkudish Thanks. I needed to flip the array to make the keys the values & the values the keys. Feel free to submit a PR. 

I'll be waiting for the PR 👍
