### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by Shaun2D2** [unicodeveloper/laravel-password#3]
Hi @unicodeveloper 

I want to contribute to this project a bit more to get my feet wet with open source projects and seems like this one is the perfect starting point for me.  I'm thinking we can do a refactor on this to separate the logic for parsing and searching the file to it's own class.  What do you think?  Overkill?  Also was looking at maybe writing out some tests. 

Just wanting feedback before I start working on it :)

Thanks,
Shaun

**Comment by unicodeveloper** [comment]
Yes, Sure you can. Feel free to go ahead and do it!. I'll create some issues and labels and assign you to them.
