### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by tillkruss** [unicodeveloper/laravel-password#9]
I'm thinking of making a password package and just came across yours.

Aside from checking the common 10k passwords I had this in mind: 
- Making the password list localizable
- Speed up common password checking (3s is not acceptable IMO)
- Checking unicode password lengths like 💩💀 equals 2 and not 4
- Checks for common patterns like: dates, repeats (aaa), sequences (abcd), and qwerty patterns

Let me know if you're interesting in me extending this package or if I should make a separate one.

**Comment by blaise-zaga** [comment]
Hi,

You're welcome to extend the package.

Thanks

**Comment by unicodeveloper** [comment]
@tillkruss I love your suggestions. Please feel free to send in implementation PRs. Thank you 🔥 👍
